### ISSUE TITLE
Editable Messages

### ISSUE THREAD

**Issue by Mahid102938** [Ink-Studios/ingot-issues#11]
On the Halloween documentation it showed all the messages and all, I assume you didn't have time so put in some basic ones like below:
http://prntscr.com/h1nfqv
http://prntscr.com/h1nftp
http://prntscr.com/h1nfxj
http://prntscr.com/h1ng1e

Anyways, we need to be able to edit all the messages. Not sure if its simpler to add an configuration option so we can set the message or for you to hard-code it into the plugin.

So the options are to either hard-code it or add a config for us to edit.
Here are a bunch of the examples/messages we already had planned from the document.
(Obviously we don't have all the messages done but you get the format/template by looking at the following)

/candy give - https://gyazo.com/d1d8e8ad28bfed56bbb9a8c8d85df77c
/candy take - https://gyazo.com/e88b57ab6b935548aa65fc045c4682ca
/candy reset - https://gyazo.com/dc22e37c5797318c49165a50a1f4613e
/candy reset all - https://gyazo.com/bd8b7955eb05b38d16165e817df79f02
No permission message - https://gyazo.com/4996fd6ece11c56366e126bbff64882e
Not enough arguments - https://gyazo.com/00513b511d7352fd4ae712090ea2e40c 
General error message - https://gyazo.com/6f72401e1ba85d77954ee50f7266ac5b

**Comment by Inkzzz** [comment]
I've made the changes. Will update you later this evening.
