### ISSUE TITLE
AdvanceTags

### ISSUE THREAD

**Issue by Inkzzz** [Ink-Studios/ingot-issues#3]
- Nametag above your head
- Nametag on the tab

Confirm the above, 

AdvanceTag is causing quite a bit of issues

**Comment by Inkzzz** [comment]
Did we get a replacement for this @Mahid102938?

**Comment by Mahid102938** [comment]
We didn't, as it isn't the plugin causing the memory leaks/high cpu usage. Would be a simple plugin to actually be made by you, I think its better to get that done custom.

**Comment by Inkzzz** [comment]
Closed as opened new repo - https://github.com/Ink-Studios/ingot-tags/issues/1
