### ISSUE TITLE
Custom Plugin Backdoors

### ISSUE THREAD

**Issue by Mahid102938** [Ink-Studios/ingot-issues#6]
Look over everything in the following list, we may have some fishy business causing things to happen on the server. Look for backdoors.

```
`Custom Plugins:
IngotCDrain - Lava and Water Creepers that drain in a 5 block radius
IngotCore - This controls our vote partys, tags in tab and above the name, chat cooldown, antiadvertising, etc
IngotDisguises - Just a custom Disguises plugin and will undisguise when you hit a player or a players hit you
IngotFools - Player Management plugin
IngotLight - /light which will give you a torch that will light up in your hand
IngotPackage - Custom CarePackages
IngotShortcuts - A custom command plugin
IngotSnowballs - A custom plugin where you combine a snowball and a slowness potion together and it'll create a slowness snowball
IngotVaults - A custom vault plugin (Anti Dupe)
IngotPrison - Prison Essentials
IngotOreGen - A skyblock plugin that will generate ores when creating a cobble generator
IngotHub - A custom server compass plugin`
```

**Comment by Mahid102938** [comment]
Custom Plugins:
IngotCDrain - Lava and Water Creepers that drain in a 5 block radius
IngotCore - This controls our vote partys, tags in tab and above the name, chat cooldown, antiadvertising, etc
IngotDisguises - Just a custom Disguises plugin and will undisguise when you hit a player or a players hit you
IngotFools - Player Management plugin
IngotLight - /light which will give you a torch that will light up in your hand
IngotNPC - a citizens addon so where you can shift right click the npc and type a command and it'll run it when ricked on
IngotPackage - Custom CarePackages
IngotShortcuts - A custom command plugin
IngotSnowballs - A custom plugin where you combine a snowball and a slowness potion together and it'll create a slowness snowball
IngotVaults - A custom vault plugin (Anti Dupe)
IngotPrison - Prison Essentials
IngotOreGen - A skyblock plugin that will generate ores when creating a cobble generator
IngotHub - A custom server compass plugin

**Comment by Inkzzz** [comment]
Down to rewrite all.
