### ISSUE TITLE
Auto Restart Announcement

### ISSUE THREAD

**Issue by ConstructorLeo** [Ink-Studios/ingot-issues#8]
The AutoRestart (part of the core plugin) doesn't announce when it'll restart.

If we can make it so it announces like this:
5m
1m
30s
10s
5s
4s
3s
2s
1s
Restart

The Auto Restart applies to all servers.

**Comment by Inkzzz** [comment]
This core will need rewriting as we do not have the source. It's on our list, but not a main priority.

**Comment by Inkzzz** [comment]
Opened a new repo for the core https://github.com/Ink-Studios/ingot-core/issues/1
